name: 'Cache and update Go caches'
description: "Restore and update Go module and build caches"
author: "Andrew LeFevre"
inputs:
  mod-key:
    description: "An explicit key for restoring and saving the module cache"
    required: true
  build-key:
    description: "An explicit key for restoring and saving the build cache"
    required: true
  github-token:
    description: "GITHUB_TOKEN as provided by secrets"
    required: true
outputs:
  mod-cache-hit:
    description: "A boolean value to indicate if the module cache was hit"
    value: ${{ steps.go-mod-cache.outputs.cache-hit }}
  build-cache-hit:
    description: "A boolean value to indicate if the build cache was hit"
    value: ${{ steps.go-build-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Get Go cache locations
      id: go-cache-loc
      shell: bash
      run: |
        echo "go-mod-cache=$(go env GOMODCACHE)" >> "${GITHUB_OUTPUT}"
        echo "go-build-cache=$(go env GOCACHE)" >> "${GITHUB_OUTPUT}"

    - name: Handle Go module cache
      id: go-mod-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-loc.outputs.go-mod-cache }}
        key: ${{ inputs.mod-key }}

    - name: Handle Go build cache
      id: go-build-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-loc.outputs.go-build-cache }}
        key: ${{ inputs.build-key }}

    - name: Install Github actions cache extension
      if: ${{ steps.go-mod-cache.outputs.cache-hit || steps.go-build-cache.outputs.cache-hit }}
      shell: bash
      run: gh extension install actions/gh-actions-cache

    - name: Delete Go module cache
      if: ${{ steps.go-mod-cache.outputs.cache-hit }}
      uses: TLizer/action-with-post-step@v1
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        main: "true" # no-op
        post: gh actions-cache delete ${{ inputs.mod-key }} --confirm
      continue-on-error: true

    - name: Delete Go build cache
      if: ${{ steps.go-build-cache.outputs.cache-hit }}
      uses: TLizer/action-with-post-step@v1
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      with:
        main: "true" # no-op
        post: gh actions-cache delete ${{ inputs.build-key }} --confirm
      continue-on-error: true
